import type { CSSProperties } from "react";

export const S: Record<string, CSSProperties> = {
  /* NAV */
  banner: {
    background: "var(--lime)",
    color: "#000",
    textAlign: "center",
    padding: "10px 16px",
    fontSize: "13px",
    fontWeight: 600,
    fontFamily: "var(--font-display)",
    letterSpacing: "0.02em",
    position: "sticky",
    top: 0,
    zIndex: 200,
  },
  nav: {
    position: "sticky",
    top: "40px",
    zIndex: 100,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "0 40px",
    height: "var(--nav-h)",
    background: "rgba(10,10,10,0.92)",
    backdropFilter: "blur(20px)",
    borderBottom: "1px solid var(--border)",
    /* needed so absolute child can center relative to full nav width */
    //position: "sticky" as const,
  },
  navCenter: {
    position: "absolute" as const,
    left: "50%",
    transform: "translateX(-50%)",
    display: "flex",
    gap: "36px",
    listStyle: "none",
    fontFamily: "var(--font-display)",
    fontSize: "14px",
    fontWeight: 500,
    color: "var(--cream-dim)",
  },
  logo: {
    fontFamily: "var(--font-display)",
    fontWeight: 800,
    fontSize: "22px",
    color: "var(--lime)",
    letterSpacing: "-0.03em",
  },
  navActions: {
    display: "flex",
    alignItems: "center",
    gap: "16px",
  },
  btnGhost: {
    background: "transparent",
    color: "var(--cream-dim)",
    fontFamily: "var(--font-display)",
    fontWeight: 500,
    fontSize: "14px",
    padding: "8px 16px",
    border: "1px solid var(--border)",
    borderRadius: "100px",
    cursor: "pointer",
    transition: "all 0.2s",
  },
  btnPrimary: {
    background: "var(--lime)",
    color: "#000",
    fontFamily: "var(--font-display)",
    fontWeight: 700,
    fontSize: "14px",
    padding: "10px 22px",
    borderRadius: "100px",
    cursor: "pointer",
    border: "none",
    transition: "all 0.2s",
    letterSpacing: "-0.01em",
  },

  /* HERO */
  hero: {
    minHeight: "100vh",
    display: "flex",
    flexDirection: "column" as const,
    justifyContent: "center",
    padding: "80px 40px 60px",
    position: "relative" as const,
    overflow: "hidden",
  },
  heroEyebrow: {
    fontFamily: "var(--font-display)",
    fontSize: "12px",
    fontWeight: 600,
    letterSpacing: "0.14em",
    color: "var(--lime)",
    textTransform: "uppercase" as const,
    marginBottom: "28px",
    display: "flex",
    alignItems: "center",
    gap: "10px",
  },
  heroTitle: {
    fontFamily: "var(--font-display)",
    fontSize: "clamp(72px, 11vw, 160px)",
    fontWeight: 800,
    lineHeight: 0.9,
    letterSpacing: "-0.04em",
    color: "var(--cream)",
    maxWidth: "1100px",
  },
  heroTitleAccent: {
    color: "transparent",
    WebkitTextStroke: "2px var(--cream-dim)",
  },
  heroSub: {
    maxWidth: "480px",
    marginTop: "48px",
    fontFamily: "var(--font-body)",
    fontSize: "17px",
    lineHeight: 1.65,
    color: "var(--text-muted)",
    borderLeft: "2px solid var(--lime)",
    paddingLeft: "20px",
  },
  heroActions: {
    display: "flex",
    alignItems: "center",
    gap: "16px",
    marginTop: "40px",
  },
  btnLarge: {
    background: "var(--lime)",
    color: "#000",
    fontFamily: "var(--font-display)",
    fontWeight: 700,
    fontSize: "16px",
    padding: "16px 36px",
    borderRadius: "100px",
    border: "none",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    gap: "10px",
  },
  btnOutlineLarge: {
    background: "transparent",
    color: "var(--cream)",
    fontFamily: "var(--font-display)",
    fontWeight: 600,
    fontSize: "16px",
    padding: "16px 36px",
    borderRadius: "100px",
    border: "1px solid rgba(240,234,214,0.2)",
    cursor: "pointer",
  },

  /* TICKER */
  ticker: {
    borderTop: "1px solid var(--border)",
    borderBottom: "1px solid var(--border)",
    padding: "14px 0",
    overflow: "hidden",
    whiteSpace: "nowrap" as const,
  },
  tickerInner: {
    display: "inline-flex",
    gap: "64px",
    animation: "ticker 28s linear infinite",
    fontFamily: "var(--font-display)",
    fontSize: "13px",
    fontWeight: 600,
    letterSpacing: "0.08em",
    textTransform: "uppercase" as const,
    color: "var(--text-muted)",
  },
  tickerDot: {
    color: "var(--lime)",
    fontSize: "20px",
    lineHeight: 1,
  },

  /* SECTION BASE */
  section: {
    padding: "120px 40px",
    position: "relative" as const,
  },
  label: {
    fontFamily: "var(--font-display)",
    fontSize: "11px",
    fontWeight: 700,
    letterSpacing: "0.14em",
    textTransform: "uppercase" as const,
    color: "var(--lime)",
    marginBottom: "20px",
  },
  h2: {
    fontFamily: "var(--font-display)",
    fontSize: "clamp(40px, 5vw, 72px)",
    fontWeight: 800,
    lineHeight: 1.0,
    letterSpacing: "-0.03em",
    color: "var(--cream)",
  },
  h2Outline: {
    color: "transparent",
    WebkitTextStroke: "1.5px var(--cream-dim)",
  },
  bodyText: {
    fontFamily: "var(--font-body)",
    fontSize: "16px",
    lineHeight: 1.7,
    color: "var(--text-muted)",
  },

  /* FEATURES */
  featuresGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(300px, 1fr))",
    gap: "2px",
    marginTop: "80px",
    border: "1px solid var(--border)",
  },
  featureCard: {
    background: "var(--surface)",
    padding: "48px 40px",
    borderRight: "1px solid var(--border)",
    transition: "background 0.3s",
    position: "relative" as const,
    overflow: "hidden",
  },
  featureIcon: {
    width: "48px",
    height: "48px",
    borderRadius: "12px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "22px",
    marginBottom: "28px",
    flexShrink: 0,
  },
  featureTitle: {
    fontFamily: "var(--font-display)",
    fontSize: "20px",
    fontWeight: 700,
    color: "var(--cream)",
    letterSpacing: "-0.02em",
    marginBottom: "12px",
  },

  /* DEMO / PREVIEW */
  demoWrap: {
    background: "var(--surface)",
    border: "1px solid var(--border)",
    borderRadius: "24px",
    overflow: "hidden",
    marginTop: "64px",
    position: "relative" as const,
  },
  demoBar: {
    background: "var(--surface-2)",
    padding: "14px 20px",
    display: "flex",
    alignItems: "center",
    gap: "8px",
    borderBottom: "1px solid var(--border)",
  },
  dot: {
    width: "12px",
    height: "12px",
    borderRadius: "50%",
  },
  demoContent: {
    display: "grid",
    gridTemplateColumns: "260px 1fr",
    minHeight: "460px",
  },
  demoSidebar: {
    background: "rgba(255,255,255,0.02)",
    borderRight: "1px solid var(--border)",
    padding: "24px 16px",
  },
  demoMain: {
    padding: "40px 48px",
  },

  /* STATS */
  statsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(4, 1fr)",
    gap: "1px",
    background: "var(--border)",
    border: "1px solid var(--border)",
    marginTop: "80px",
  },
  statCard: {
    background: "var(--bg)",
    padding: "48px 40px",
    textAlign: "center" as const,
  },
  statNum: {
    fontFamily: "var(--font-display)",
    fontSize: "64px",
    fontWeight: 800,
    letterSpacing: "-0.04em",
    color: "var(--cream)",
    lineHeight: 1,
    animation: "count-up 0.8s ease both",
  },
  statLabel: {
    fontFamily: "var(--font-body)",
    fontSize: "14px",
    color: "var(--text-muted)",
    marginTop: "8px",
  },

  /* TESTIMONIALS */
  testimonialGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(3, 1fr)",
    gap: "20px",
    marginTop: "64px",
  },
  testimonialCard: {
    background: "var(--surface)",
    border: "1px solid var(--border)",
    borderRadius: "16px",
    padding: "36px 32px",
    transition: "border-color 0.3s",
  },
  quote: {
    fontFamily: "var(--font-body)",
    fontSize: "15px",
    lineHeight: 1.7,
    color: "var(--cream-dim)",
    marginBottom: "28px",
    fontStyle: "italic",
  },
  avatarRow: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
  },
  avatar: {
    width: "40px",
    height: "40px",
    borderRadius: "50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontFamily: "var(--font-display)",
    fontWeight: 700,
    fontSize: "15px",
    color: "#000",
    flexShrink: 0,
  },
  avatarName: {
    fontFamily: "var(--font-display)",
    fontWeight: 600,
    fontSize: "14px",
    color: "var(--cream)",
  },
  avatarRole: {
    fontFamily: "var(--font-body)",
    fontSize: "12px",
    color: "var(--text-muted)",
    marginTop: "2px",
  },

  /* PRICING */
  pricingGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(3, 1fr)",
    gap: "20px",
    marginTop: "64px",
  },
  pricingCard: {
    background: "var(--surface)",
    border: "1px solid var(--border)",
    borderRadius: "20px",
    padding: "48px 36px",
    position: "relative" as const,
    overflow: "hidden",
    transition: "transform 0.3s, border-color 0.3s",
  },
  pricingCardFeatured: {
    background: "var(--lime)",
    border: "none",
    borderRadius: "20px",
    padding: "48px 36px",
    position: "relative" as const,
    overflow: "hidden",
    transform: "scale(1.04)",
  },
  planName: {
    fontFamily: "var(--font-display)",
    fontWeight: 700,
    fontSize: "13px",
    letterSpacing: "0.1em",
    textTransform: "uppercase" as const,
    marginBottom: "24px",
  },
  planPrice: {
    fontFamily: "var(--font-display)",
    fontWeight: 800,
    fontSize: "56px",
    letterSpacing: "-0.04em",
    lineHeight: 1,
  },
  planPer: {
    fontFamily: "var(--font-body)",
    fontSize: "14px",
    opacity: 0.6,
    marginLeft: "4px",
  },

  /* CTA */
  ctaSection: {
    padding: "120px 40px",
    textAlign: "center" as const,
    position: "relative" as const,
    overflow: "hidden",
  },

  /* FOOTER */
  footer: {
    borderTop: "1px solid var(--border)",
    padding: "64px 40px 40px",
  },
  footerGrid: {
    display: "grid",
    gridTemplateColumns: "2fr 1fr 1fr 1fr",
    gap: "48px",
    marginBottom: "64px",
  },
  footerLink: {
    display: "block",
    fontFamily: "var(--font-body)",
    fontSize: "14px",
    color: "var(--text-muted)",
    marginBottom: "12px",
    transition: "color 0.2s",
  },
  footerHeading: {
    fontFamily: "var(--font-display)",
    fontWeight: 700,
    fontSize: "13px",
    color: "var(--cream)",
    marginBottom: "20px",
    letterSpacing: "0.04em",
    textTransform: "uppercase" as const,
  },
};
